- name: nginx installation
  hosts: web
  become: yes
  tasks:
  - name: nginx install
    ansible.builtin.package:
      name: nginx
      state: present
  - name: start the nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  - name: install zip
    ansible.builtin.package:
      name: zip
      state: present
  - name: install gcc
    ansible.builtin.package:
      name: gcc
      state: present
