- name: Variables
  hosts: local
  connection: local
  vars: 
    COURSE: Devsecops
    DURATION: 120hrs
    TRAINER: Shiva
  tasks:
  - name: Print the message using Variables
    ansible.builtin.debug:
      msg: "I am learning {{ COURSE }}, duration is: {{ DURATION }}, trainer name is: {{ TRAINER }"