- name: variables from file
  hosts: local
  connection: local
  vars_files:
  - course.yaml
  tasks:
  - name: variables from vars from file
    ansible.builtin.debug:
      msg: "learning {{ COURSE}} DURATION{{ DURATION}} TRAINER {{ TRAINER}}"