- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item }}"
      stated: installed
    loop:
    - gcc
    - zip
    - mysql
